# Generated by Django 3.2.9 on 2021-11-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consumer',
            new_name='UserInfo',
        ),
    ]
