# Generated by Django 3.2.9 on 2021-11-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_rename_consumer_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='name',
        ),
    ]
