# Generated by Django 3.2.9 on 2021-11-29 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_remove_userinfo_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinfo',
            table='userinfo',
        ),
    ]
