# Generated by Django 3.2.9 on 2021-11-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('show_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('cast', models.TextField()),
                ('country', models.CharField(max_length=200)),
                ('release_year', models.IntegerField(null=True)),
                ('rating', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=60)),
                ('listed_in', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
